#!/usr/bin/env bash

declare -a STORAGE_KEYS
declare -A STORAGE_PROMPTS

storage_add() {
  STORAGE_KEYS+=($1)
  STORAGE_PROMPTS[${STORAGE_KEYS[-1]}]=$2
}

storage_show() {
  for STORAGE_KEY in "${STORAGE_KEYS[@]}"
  do
    STORAGE_PROMPT=${STORAGE_PROMPTS[${STORAGE_KEY}]}
    echo "${STORAGE_KEY}(${STORAGE_PROMPT}): ${!STORAGE_KEY}"
  done
}

print_settings_storage() {
  for STORAGE_KEY in "${STORAGE_KEYS[@]}"
  do
    echo "${STORAGE_KEY}=${!STORAGE_KEY}"
  done
}

print_ssh_config() {
  echo "Host *"
  echo "ProxyCommand connect -H ${STORAGE_HTTP_PROXY_USER}@${STORAGE_HTTP_PROXY} %h %p"
}

sync_config() {
  if [ ! -e "$2" ] || [[ $($1) != $(cat "$2") ]]
  then
    echo "$1 $2 sync"
    $1 > "$2"
  else
    echo "$1 $2 not change"
  fi
}

sync_git_config() {
  if [[ "$3" != $(git config "$1" "$2") ]]
  then
    echo "git config $1 $2 $3"
    git config "$1" "$2" "$3"
  else
    echo "git config $1 $2 not change"
  fi
}



for GIT_HOST_DIR in $(ls -p1 ~/All/git)
do
  if [[ "${GIT_HOST_DIR}" =~ .+/ ]]
  then
    GIT_HOST_DIR=${GIT_HOST_DIR%/}
    GIT_HOST_DIR_UPPER=${GIT_HOST_DIR^^}
    storage_add STORAGE_GIT_${GIT_HOST_DIR_UPPER}_USER_NAME "git config ${GIT_HOST_DIR} user.name"
    storage_add STORAGE_GIT_${GIT_HOST_DIR_UPPER}_USER_EMAIL "git config ${GIT_HOST_DIR} user.email"
  fi
done
storage_add STORAGE_HTTP_PROXY "http proxy[:port]"
storage_add STORAGE_HTTP_PROXY_USER "http proxy user"
storage_add STORAGE_HTTP_PROXY_PASSWORD "http proxy password"

if [ -e ~/.settings_storage ]
then
  source ~/.settings_storage
fi

for STORAGE_KEY in "${STORAGE_KEYS[@]}"
do
  if [ ! -v ${STORAGE_KEY} ]
  then
    STORAGE_PROMPT=${STORAGE_PROMPTS[${STORAGE_KEY}]}
    read -p "${STORAGE_PROMPT}: " "${STORAGE_KEY}"
  fi
done

storage_show



sync_config print_settings_storage ~/.settings_storage

for GIT_HOST_DIR in $(ls -p1 ~/All/git)
do
  if [[ "${GIT_HOST_DIR}" =~ .+/ ]]
  then
    GIT_HOST_DIR=${GIT_HOST_DIR%/}
    GIT_HOST_DIR_UPPER=${GIT_HOST_DIR^^}
    GIT_HOST_PATHSTR='~'/All/git/${GIT_HOST_DIR}
    GIT_HOST_CONFIGSTR='~'/All/git/${GIT_HOST_DIR}/.gitconfig
    GIT_HOST_CONFIG=~/All/git/${GIT_HOST_DIR}/.gitconfig
    GIT_VAR_USER_NAME=STORAGE_GIT_${GIT_HOST_DIR_UPPER}_USER_NAME
    GIT_VAR_USER_EMAIL=STORAGE_GIT_${GIT_HOST_DIR_UPPER}_USER_EMAIL
    sync_git_config --global "includeIf.gitdir/i:${GIT_HOST_PATHSTR}/.path" "${GIT_HOST_CONFIGSTR}"
    sync_git_config --file="${GIT_HOST_CONFIG}" user.name "${!GIT_VAR_USER_NAME}"
    sync_git_config --file="${GIT_HOST_CONFIG}" user.email "${!GIT_VAR_USER_EMAIL}"
  fi
done

sync_config print_ssh_config ~/.ssh/config

export HTTP_PROXY_PASSWORD=${STORAGE_HTTP_PROXY_PASSWORD}
